# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogParser',
            fields=[
                ('LogFileID', models.AutoField(primary_key=True, serialize=False)),
                ('LogFileDate', models.DateTimeField(auto_now_add=True)),
                ('LogFileName', models.FileField(upload_to='./LogFiles/')),
                ('LogFileParsed', models.SmallIntegerField(default=0, max_length=1)),
            ],
        ),
    ]
