# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logParser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logparser',
            name='LogFileParsed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
