# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildingManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='systemLogs',
            fields=[
                ('SysLogID', models.AutoField(primary_key=True, serialize=False)),
                ('SysLogMACAddress', models.CharField(blank=True, max_length=30)),
                ('SysLogRSSI', models.CharField(max_length=10)),
                ('SysLogLongitude', models.CharField(blank=True, max_length=50)),
                ('SysLogLatitude', models.CharField(blank=True, max_length=50)),
                ('SysLogBuildingIDFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildingManager.Buildings')),
                ('SysLogFloorIDFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildingManager.Floors')),
            ],
        ),
    ]
