# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('BuildingID', models.AutoField(primary_key=True, serialize=False)),
                ('BuildingName', models.CharField(max_length=255)),
                ('BuildingAlias', models.CharField(blank=True, max_length=255)),
                ('BuildingAddress', models.CharField(max_length=255)),
                ('BuildingLongitude', models.CharField(blank=True, max_length=50)),
                ('BuildingLatitude', models.CharField(blank=True, max_length=50)),
                ('Active', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campuses',
            fields=[
                ('CampusID', models.AutoField(primary_key=True, serialize=False)),
                ('CampusName', models.CharField(max_length=255)),
                ('CampusAlias', models.CharField(blank=True, max_length=255)),
                ('CampusAddress', models.CharField(max_length=255)),
                ('CampusLongitude', models.CharField(blank=True, max_length=50)),
                ('CampusLatitude', models.CharField(blank=True, max_length=50)),
                ('Active', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('FloorID', models.AutoField(primary_key=True, serialize=False)),
                ('FloorNumber', models.CharField(max_length=30)),
                ('FloorMAP', models.CharField(blank=True, max_length=30)),
                ('FloorAlias', models.CharField(blank=True, max_length=30)),
                ('BuildingIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingManager.Buildings')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterests',
            fields=[
                ('POIID', models.AutoField(primary_key=True, serialize=False)),
                ('POIAlias', models.CharField(blank=True, max_length=255)),
                ('POILongitude', models.CharField(blank=True, max_length=50)),
                ('POILatitude', models.CharField(blank=True, max_length=50)),
                ('Active', models.SmallIntegerField(default=0)),
                ('FloorIDFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingManager.Floors')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='CampusIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingManager.Campuses'),
        ),
    ]
