# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='CampusIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='buildingManager.Campuses'),
        ),
        migrations.AlterField(
            model_name='floors',
            name='BuildingIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildingManager.Buildings'),
        ),
        migrations.AlterField(
            model_name='floors',
            name='FloorMAP',
            field=models.FileField(upload_to='./buildingManager/maps/'),
        ),
        migrations.AlterField(
            model_name='pointofinterests',
            name='FloorIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='buildingManager.Floors'),
        ),
    ]
