# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingManager', '0002_auto_20161116_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterests',
            name='FloorIDFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi', to='buildingManager.Floors'),
        ),
    ]
